{
  "additionalMetadata": {
    "cna": "postgresql",
    "cveId": "CVE-2024-2044",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/pgadmin-org/pgadmin4/issues/7258",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LUYN2JXKKHFSVTASH344TBRGWDH64XQV/",
      "https://www.shielder.com/advisories/pgadmin-path-traversal_leads_to_unsafe_deserialization_and_rce/"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://pypi.org",
        "cpes": [
          "cpe:2.3:a:pgadmin:pgadmin:*:*:*:*:*:postgresql:*:*",
          "cpe:2.3:a:pgadmin:pgadmin_4:*:*:*:*:*:postgresql:*:*"
        ],
        "packageName": "pgAdmin4",
        "packageType": "python",
        "product": "pgAdmin 4",
        "repo": "https://github.com/pgadmin-org/pgadmin4",
        "vendor": "pgadmin.org",
        "versions": [
          {
            "lessThan": "8.4",
            "status": "affected",
            "version": "0",
            "versionType": "python"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}