{
  "additionalMetadata": {
    "cna": "psf",
    "cveId": "CVE-2024-3219",
    "description": "There is a MEDIUM severity vulnerability affecting CPython.\n\nThe\n “socket” module provides a pure-Python fallback to the \nsocket.socketpair() function for platforms that don’t support AF_UNIX, \nsuch as Windows. This pure-Python implementation uses AF_INET or \nAF_INET6 to create a local connected pair of sockets. The connection \nbetween the two sockets was not verified before passing the two sockets \nback to the user, which leaves the server socket vulnerable to a \nconnection race from a malicious local peer.\n\nPlatforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.",
    "needsReview": true,
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "http://www.openwall.com/lists/oss-security/2024/07/29/3",
      "https://github.com/python/cpython/issues/122133",
      "https://github.com/python/cpython/pull/122134",
      "https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/"
    ],
    "toDos": [
      "Monitor for fixed versions"
    ]
  },
  "adp": {
    "affected": [
      {
        "cpes": [
          "cpe:2.3:a:python:python:*:*:*:*:*:windows:*:*"
        ],
        "platforms": [
          "Windows"
        ],
        "product": "CPython",
        "vendor": "Python Software Foundation",
        "versions": [
          {
            "lessThanOrEqual": "3.13.0b4",
            "status": "affected",
            "version": "3.5",
            "versionType": "python"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}