{
  "additionalMetadata": {
    "cna": "psf",
    "cveId": "CVE-2024-4030",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e",
      "https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d",
      "https://github.com/python/cpython/issues/118486",
      "https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/"
    ]
  },
  "adp": {
    "affected": [
      {
        "cpes": [
          "cpe:2.3:a:python:python:*:*:*:*:*:windows:*:*"
        ],
        "platforms": [
          "Windows"
        ],
        "product": "CPython",
        "repo": "https://github.com/python/cpython",
        "vendor": "Python Software Foundation",
        "versions": [
          {
            "lessThan": "3.13.0b1",
            "status": "affected",
            "version": "3.13.0a1",
            "versionType": "python"
          },
          {
            "lessThan": "3.12.4",
            "status": "affected",
            "version": "0",
            "versionType": "python"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}